const fs = require('fs');
const path = require('path');
const p = path.join(__dirname, 'batman-beyaz-esya.html');
let h = '';
h += '<!DOCTYPE html>\n<html lang="tr">\n<head>\n';
h += '<meta charset="UTF-8"/>\n';
h += '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n';
h += '<title>Batman Beyaz Eşya Tamircisi | Çamaşır, Bulaşık Makinesi, Buzdolabı, Fırın, Şofben Tamiri</title>\n';
h += '<meta name="description" content="Batman\'da beyaz eşya tamiri. Çamaşır makinesi, bulaşık makinesi, buzdolabı, derin dondurucu, fırın ve şofben tamiri. Aynı gün servis garantisi ile 7/24 profesyonel hizmet. +90 537 447 16 39"/>\n';
h += '<meta name="keywords" content="batman beyaz eşya tamiri, batman çamaşır makinesi tamiri, batman bulaşık makinesi tamiri, batman buzdolabı tamiri, batman derin dondurucu tamiri, batman fırın tamiri, batman şofben tamiri, batman teknik servis, batman beyaz eşya servisi, batman ev aletleri tamiri, batman acil teknik servis, batman aynı gün servis"/>\n';
h += '<meta name="robots" content="index, follow"/>\n';
h += '<meta name="author" content="Batman Beyaz Eşya Tamir Teknik Servis"/>\n';
h += '<link rel="canonical" href="https://batmanbeyazesiyatamir.com/"/>\n';
h += '<meta property="og:type" content="website"/>\n';
h += '<meta property="og:title" content="Batman Beyaz Eşya Tamircisi – Profesyonel Teknik Servis"/>\n';
h += '<meta property="og:description" content="Batman\'da beyaz eşya tamiri. Çamaşır makinesi, bulaşık makinesi, buzdolabı, fırın, şofben ve derin dondurucu tamiri. 7/24 hizmet."/>\n';
h += '<meta property="og:locale" content="tr_TR"/>\n';
h += '<meta property="og:site_name" content="Batman Beyaz Eşya Tamir"/>\n';
h += '<meta name="twitter:card" content="summary_large_image"/>\n';
h += '<meta name="twitter:title" content="Batman Beyaz Eşya Tamircisi"/>\n';
h += '<meta name="twitter:description" content="Batman\'da çamaşır makinesi, bulaşık makinesi, buzdolabı, fırın ve şofben tamiri. 7/24 aynı gün servis."/>\n';
h += '<script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"Batman Beyaz Eşya Tamircisi","description":"Batman\'da çamaşır makinesi, bulaşık makinesi, buzdolabı, derin dondurucu, fırın ve şofben tamiri. Aynı gün servis garantisi ile profesyonel beyaz eşya bakım ve onarım hizmeti.","telephone":"+905374471639","address":{"@type":"PostalAddress","streetAddress":"Yeni, Raman Cd. No: 43 D:B","addressLocality":"Batman Merkez","postalCode":"72070","addressRegion":"Batman","addressCountry":"TR"},"geo":{"@type":"GeoCoordinates","latitude":37.8812,"longitude":41.1351},"openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],"opens":"08:00","closes":"23:00"}],"priceRange":"₺₺","areaServed":"Batman Merkez"}</script>\n';
h += '<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Batman\'da çamaşır makinesi tamiri hizmeti veriyor musunuz?","acceptedAnswer":{"@type":"Answer","text":"Evet, Batman\'da tüm marka ve model çamaşır makinelerinde tamir hizmeti sunuyoruz."}},{"@type":"Question","name":"Buzdolabı tamiri ne kadar sürer?","acceptedAnswer":{"@type":"Answer","text":"Buzdolabı arızasının türüne bağlı olarak çoğu tamir aynı gün içinde tamamlanmaktadır."}},{"@type":"Question","name":"Fırın tamiri için hangi markaları kabul ediyorsunuz?","acceptedAnswer":{"@type":"Answer","text":"Tüm marka ve model fırınları tamir ediyoruz."}},{"@type":"Question","name":"Acil durumlarda ne kadar hızlı müdahale ediyorsunuz?","acceptedAnswer":{"@type":"Answer","text":"Batman\'da acil beyaz eşya arızalarında 30-60 dakika içinde adresinize ulaşıyoruz."}},{"@type":"Question","name":"Garanti belgesi veriyor musunuz?","acceptedAnswer":{"@type":"Answer","text":"Evet, tüm tamir işlemlerimizde orijinal yedek parça kullanımı ve garanti belgesi sunuyoruz."}}]}</script>\n';
h += '<link rel="preconnect" href="https://fonts.googleapis.com"/>\n';
h += '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>\n';
h += '<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800;900&family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>\n';
h += '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>\n';
h += '<style>\n';
h += require('fs').readFileSync(path.join(__dirname, 'styles.css'), 'utf8');
h += '</style>\n</head>\n<body>\n';
// Write head
fs.writeFileSync(p, h, 'utf8');
console.log('Head written');
